### ISSUE TITLE
Allow distribution with Vital name

### ISSUE THREAD

**Issue by falkTX** [mtytel/vital#1]
Hi, thanks a lot for making vital opensource!

I was about to try it out, but readme states:

> Do not use the name "Vital", "Vital Audio", "Tytel" or "Matt Tytel" for marketing or to name any distribution of binaries built with this source

Would be weird to have vital packaged but having to use an alternative name.

**Comment by diovudau** [comment]
Can the name for the Archlinux AUR, which consist of compile-instructions/scripts contain "Vital" ? 
There are no binaries in a potential AUR buildscript and every user has to build themselves locally.

**Comment by mtytel** [comment]
I'm might be ok giving permission on a case-by-case basis to redistribute binaries with the name "Vital", but only from binaries I've built myself for now. So if someone makes a "vital" package using the binaries from the site just let me know.

There are things like API keys and accessing certain web services that I don't want people to use with modified versions so I'm not going to publish to this repository. Having an account on the site is also an important part for a lot of features so if people don't go through that process it won't have all the functionality.

**Comment by falkTX** [comment]
Sounds fair.
If we disable those features and any access to vital.io, are you ok with "Vitalium" as a sorta community package/version?

**Comment by alex-tee** [comment]
@mtytel you might want to consider what I'm doing for zrythm. I give permission to specific distros, and allow derivatives of those distros to re-use changes made by allowed distros.

https://git.sr.ht/~alextee/zrythm/tree/HEAD/TRADEMARKS.md

otherwise, I'd suggest deciding on a name for clones so all distros use a common name

**Comment by mtytel** [comment]
Thinking about it more, I might just want people to go to the site to get "Vital".

But yeah right now if you build from this source it shows up as "Vial" (missing t) with a triangle logo. I think I'm good with "Vitalium" if you wanted to do that, let me know if you go that route.

**Comment by tank-trax** [comment]
does that mean it can be distributed it as `Vial`? 

Was this intentional or is it a typo?

```
<JUCERPROJECT id="C9WuMW" name="Vial" projectType="audioplug" version="1.0.6"
``

**Comment by unfa** [comment]
I've made a logo design a few years back thinking about Vital, maybe it could be used for the "community edition"?
![V logo](https://user-images.githubusercontent.com/491704/108923502-3dfaeb80-7639-11eb-8518-1f8f010be2d0.png)

**Comment by unfa** [comment]
What do you think of a name "Viral"?
Also has medical connotations, sounds very close yet distinctly different.

**Comment by alex-tee** [comment]
> What do you think of a name "Viral"?
> Also has medical connotations, sounds very close yet distinctly different.

sounds negative IMO, I like the 3 options mentioned in the various chatrooms so far: vial/valium (lol)/vitalium

**Comment by unfa** [comment]
I think I'd go for Valium then. I find it a hillarious name for a synth.

**Comment by Be-ing** [comment]
> What do you think of a name "Viral"?

That could potentially be confused with the Access Virus synthesizers.

**Comment by apoorv569** [comment]
Vitalized.

**Comment by tank-trax** [comment]
Not into Vial because it sounds like the word vile

Not into Valium either. Makes me think of the expression "take a valium" which is old school for "chill out".

I do like Vitalium though because it sounds like an element in the periodic table and it's a modification of the word Vital.

**Comment by lokkiikkol** [comment]
imho definitely go with Vitalium, it will help people that are searching for vital in apt or whatever, since it fully contains "vital".

**Comment by FloraCanou** [comment]
Isn't "valium" also a trademark? (see https://en.wiktionary.org/wiki/Valium)

Go for vitalium +1.

**Comment by unfa** [comment]
Yeah, Vitalium seems like a good idea. It will show up on package manager searches, it's clearly showing the origin, but it's quite different.

**Comment by ist157** [comment]
Like vscode vs vscodium

**Comment by kurtbusch420** [comment]
Like vscode vs vscodium

**Comment by Be-ing** [comment]
So is anyone volunteering to maintain the repository for Vitalium? @falkTX? I already have some fixes for the build system in [my fork](https://github.com/Be-ing/vital/tree/build_system) (#5).

**Comment by falkTX** [comment]
I already began as well, there is a lot of missing includes in the code from my quick checks.
But I am in the middle of a move, cant do anything about this for a few days.

**Comment by Be-ing** [comment]
@falkTX would you at least be able to create a repo so we can start collecting pull requests? It's fine if those don't get merged immediately, but it would help to have somewhere to coordinate efforts.

**Comment by falkTX** [comment]
> @falkTX would you at least be able to create a repo so we can start collecting pull requests? It's fine if those don't get merged immediately, but it would help to have somewhere to coordinate efforts.

next week. I already turned off the desktop pc and screens.

**Comment by tank-trax** [comment]
I have built the standalone, the VST2 and VST3 with success however the LV2 cannot display the UI

**Comment by ycollet** [comment]
And what about vitalibre ?

**Comment by diovudau** [comment]
I think is has been already decided, right?
If @mtytel likes Vitalium and @falkTX  as well, who wants to create the basis for a package, then that is already very good.

I personally think that Vitalium is a good name. It is a serious name for a serious piece of software.  Sometimes you gotta stop with the play on words.

**Comment by Be-ing** [comment]
> Like vscode vs vscodium

Or Chrome vs Chromium

**Comment by ycollet** [comment]
Noted !
Vitalium is great too :)

**Comment by lokkiikkol** [comment]
Calm down and take a Vitalin... :)

**Comment by edogawa23** [comment]
How about "Élan"? [https://de.wikipedia.org/wiki/%C3%89lan_vital](url)

The Accent might be problematic, so maybe without in the name, but with it in the Logo?

Just an idea but maybe not the worst one...

**Comment by falkTX** [comment]
> I think is has been already decided, right?
> If @mtytel likes Vitalium and @falkTX as well, who wants to create the basis for a package, then that is already very good.

this.

there is an answer already. lets not bother Matt with this anymore since the questions are answered now.
