### ISSUE TITLE
Please create a versioned source tarball/zip

### ISSUE THREAD

**Issue by nd-btw** [mtytel/vital#13]
Some Linux distributions require one in their package inclusion guidelines. For example: [Solus package request guidelines](https://getsol.us/articles/packaging/request-a-package/en/) 

Releasing these will surely be a boon to the widespread adoption of this incredible software. Thanks for reading.

**Comment by falkTX** [comment]
You can't package vital as-is, so this is not really relevant.

**Comment by mtytel** [comment]
Yeah I'm going to distribute the only "Vital" builds myself, though I'll probably make exceptions for binary only builds.
