### ISSUE TITLE
Is it okay to credit original plugin is forked version?

### ISSUE THREAD

**Issue by falkTX** [mtytel/vital#17]
A small quick question.
Are you okay with having something like this:

![image](https://user-images.githubusercontent.com/1334853/109948476-46ef5b00-7cd2-11eb-8780-d51e40d3684e.png)

**Comment by mtytel** [comment]
I've been thinking about this a bit.

I'm good with this as long as Vitalium is feature consistent with the Vital source.

I should have brought this up about the Vitalium name too. I think it's only appropriate to call it 'Vitalium' if the changes are only compatibility fixes and bug fixes and things like that. If people start adding features or changing functionality in Vitalium I would be uncomfortable with how close the names are. I think this is the plan for Vitalium anyway right?

Anyway I'm good with the above (Vitalium name and credit) if there are no feature additions to Vitalium.

If someone does create a fork and adds features I would want them to change the name so it doesn't contain "Vital".

**Comment by falkTX** [comment]
That is quite fair, thanks!

And yes, besides bug-fixes or general UX improvements I do not intend to change anything deep within the plugin. The purpose is to keep compatibility with main Vital.
I did already remove stuff like login, download etc which requires authentication. And changed the keyboard modifier from Alt to Ctrl, as otherwise I cannot use them. (on many WMs on Linux, Alt+left-click is to move a window and Alt+right-click to resize)

There are sadly still quite a few crashes with the plugin, and other oddities.
The main one being that, on some desktops, the plugin is rendered below the WM decoration. From what I can see, these are present in Vital too.

So Vitalium has feature parity, even on bugs :)
