### ISSUE TITLE
Licensing of presets included with free version

### ISSUE THREAD

**Issue by riban-bw** [mtytel/vital#18]
Is it permissible to distribute LV2 versions of the _Factory Content_ patches availble with the free version of Vital? Users may wish to run the LV2 plugin headless and hence be unable to access the .vital patches. (This is my use case.) We have vitalium running on Zynthian and it would be cool to be able to distribute the presets too for good out-of-box-experience for users.

**Comment by mtytel** [comment]
No, you can read why in this other issue: https://github.com/mtytel/vital/issues/15

**Comment by riban-bw** [comment]
Yep! Fully understood. Thanks for the prompt response and apologies for not searching closed issues before posting. It may be advantageous to explicitly state this constraint on the reader, similar to how you describe other requirements. It may also be advantageous to be able to purchase LV2 versions of the presets from your store for those using a plug-in version of the synth. I appreciate this may return too low revenue to warrant the overhead.
