### ISSUE TITLE
can*t compile  VST/juce_VST_Wrapper.cpp:87:10: Error 

### ISSUE THREAD

**Issue by artbody** [mtytel/vital#19]
```
 make
....
make -C standalone/builds/linux CONFIG=Release SIMDFLAGS="-msse2" GLFLAGS="" BUILD_DATE="2021 03 27 00 37"
make[1]: Verzeichnis „/usr/src/fremd/vital/standalone/builds/linux“ wird betreten
make[1]: Für das Ziel „all“ ist nichts zu tun.
make[1]: Verzeichnis „/usr/src/fremd/vital/standalone/builds/linux“ wird verlassen
make -C plugin/builds/linux_vst VST3 CONFIG=Release AR=gcc-ar SIMDFLAGS="-msse2" GLFLAGS="" BUILD_DATE="2021 03 27 00 37"
make[1]: Verzeichnis „/usr/src/fremd/vital/plugin/builds/linux_vst“ wird betreten
Compiling include_juce_audio_plugin_client_VST3.cpp
In Datei, eingebunden von ../../../third_party/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp:26,
                 von ../../JuceLibraryCode/include_juce_audio_plugin_client_VST3.cpp:9:
../../../third_party/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3_Wrapper.cpp:32:24: Warnung: mehrere Token am Ende der Direktive #include
   32 |  #include <arpa/inet.h>^M
      |                        ^
In Datei, eingebunden von ../../../third_party/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp:26,
                 von ../../JuceLibraryCode/include_juce_audio_plugin_client_VST3.cpp:9:
../../../third_party/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3_Wrapper.cpp:33:7: Warnung: mehrere Token am Ende der Direktive #endif [-Wendif-labels]
   33 | #endif^M
      |       ^
In Datei, eingebunden von ../../../third_party/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp:26,
                 von ../../JuceLibraryCode/include_juce_audio_plugin_client_VST3.cpp:9:
../../../third_party/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3_Wrapper.cpp:69:11: schwerwiegender Fehler: pluginterfaces/vst2.x/vstfxstore.h: Datei oder Verzeichnis nicht gefunden
   69 |  #include "pluginterfaces/vst2.x/vstfxstore.h"
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Kompilierung beendet.
make[1]: *** [Makefile:206: build/intermediate/Release/include_juce_audio_plugin_client_VST3_dd633589.o] Fehler 1
make[1]: Verzeichnis „/usr/src/fremd/vital/plugin/builds/linux_vst“ wird verlassen
make: *** [Makefile:100: vst3] Fehler 2

```

**Comment by artbody** [comment]
make install_standalone
make -C standalone/builds/linux CONFIG=Release SIMDFLAGS="-msse2" GLFLAGS="" BUILD_DATE="2021 03 27 00 48"
make[1]: Verzeichnis „/usr/src/fremd/vital/standalone/builds/linux“ wird betreten
make[1]: Für das Ziel „all“ ist nichts zu tun.
make[1]: Verzeichnis „/usr/src/fremd/vital/standalone/builds/linux“ wird verlassen
install -d /usr/share/icons/hicolor//16x16/apps /usr/share/icons/hicolor//22x22/apps /usr/share/icons/hicolor//24x24/apps /usr/share/icons/hicolor//32x32/apps
install -d /usr/share/icons/hicolor//48x48/apps /usr/share/icons/hicolor//64x64/apps /usr/share/icons/hicolor//128x128/apps /usr/share/icons/hicolor//256x256/apps
install -d /usr/share/pixmaps
cp images/vital.xpm /usr/share/pixmaps/vital.xpm
cp: der Aufruf von stat für 'images/vital.xpm' ist nicht möglich: Datei oder Verzeichnis nicht gefunden
make: *** [Makefile:77: install_icons] Fehler 1

**Comment by artbody** [comment]
looks like there is no way to compile this vital on a gentoo linux

**Comment by artbody** [comment]
`` make
make -C standalone/builds/linux CONFIG=Release SIMDFLAGS="-msse2" GLFLAGS="" BUILD_DATE="2021 03 30 11 21"
make[1]: Verzeichnis ,,/usr/src/fremd/vital/standalone/builds/linux" wird betreten
Compiling common.cpp
In Datei, eingebunden von ../../../src/unity_build/common.cpp:25:
../../../src/common/synth_gui_interface.cpp: In Elementfunktion »void SynthGuiInterface::setGuiSize(float)«:
../../../src/common/synth_gui_interface.cpp:199:103: Warnung: »const juce::Displays::Display& juce::Displays::findDisplayForPoint(juce::Point<int>, bool) const« ist veraltet [-Wdeprecated-declarations]
  199 | y = Desktop::getInstance().getDisplays().findDisplayForPoint(position);
      |                                                                      ^

In Datei, eingebunden von ../../../third_party/JUCE/modules/juce_core/system/juce_StandardHeader.h:69,
                 von ../../../third_party/JUCE/modules/juce_core/juce_core.h:20,
                 von ../../../third_party/JUCE/modules/juce_audio_basics/juce_audio_basics.h:53,
                 von ../../JuceLibraryCode/JuceHeader.h:17,
                 von ../../../src/common/border_bounds_constrainer.h:19,
                 von ../../../src/common/border_bounds_constrainer.cpp:17,
                 von ../../../src/unity_build/common.cpp:18:
../../../third_party/JUCE/modules/juce_gui_basics/desktop/juce_Displays.h:139:37: Anmerkung: hier deklariert
  139 |     JUCE_DEPRECATED (const Display& findDisplayForPoint (Point<int>, bool isPhysical = false) const noexcept);
      |                                     ^~~~~~~~~~~~~~~~~~~
../../../third_party/JUCE/modules/juce_core/system/juce_PlatformDefs.h:294:57: Anmerkung: in Definition des Makros »JUCE_DEPRECATED«
  294 |  #define JUCE_DEPRECATED(functionDef)                   functionDef JUCE_DEPRECATED_ATTRIBUTE
      |                                                         ^~~~~~~~~~~
Compiling interface_editor_components.cpp
In Datei, eingebunden von ../../../src/unity_build/interface_editor_components.cpp:23:
../../../src/interface/editor_components/synth_preset_selector.cpp: In Elementfunktion »void SynthPresetSelector::openSkinDesigner()«:
../../../src/interface/editor_components/synth_preset_selector.cpp:395:79: Warnung: »const juce::Displays::Display& juce::Displays::getMainDisplay() const« ist veraltet [-Wdeprecated-declarations]
  395 |   Rectangle<int> bounds = Desktop::getInstance().getDisplays().getMainDisplay().userArea.reduced(20);
      |                                                                
In Datei, eingebunden von ../../../third_party/JUCE/modules/juce_core/system/juce_StandardHeader.h:69,
                 von ../../../third_party/JUCE/modules/juce_core/juce_core.h:203,
                 von ../../../third_party/JUCE/modules/juce_audio_basics/juce_audio_basics.h:53,
                 von ../../JuceLibraryCode/JuceHeader.h:17,
                 von ../../../src/interface/editor_components/lfo_editor.h:19,
                 von ../../../src/interface/editor_components/lfo_editor.cpp:17,
                 von ../../../src/unity_build/interface_editor_components.cpp:17:
../../../third_party/JUCE/modules/juce_gui_basics/desktop/juce_Displays.h:139:37: Anmerkung: hier deklariert
  139 |     JUCE_DEPRECATED (const Display& findDisplayForPoint (Point<int>, bool isPhysical = false) const noexcept);
      |                                     ^~~~~~~~~~~~~~~~~~~
../../../third_party/JUCE/modules/juce_core/system/juce_PlatformDefs.h:294:57: Anmerkung: in Definition des Makros »JUCE_DEPRECATED«
  294 |  #define JUCE_DEPRECATED(functionDef)                   functionDef JUCE_DEPRECATED_ATTRIBUTE
      |                                                         ^~~~~~~~~~~
Compiling interface_editor_sections.cpp
Compiling interface_editor_sections2.cpp
Compiling interface_look_and_feel.cpp
Compiling interface_wavetable.cpp
Compiling standalone.cpp
Compiling synthesis.cpp
Compiling BinaryData.cpp
Compiling include_juce_audio_basics.cpp
Compiling include_juce_audio_devices.cpp
Compiling include_juce_audio_formats.cpp
Compiling include_juce_audio_processors.cpp
Compiling include_juce_audio_utils.cpp
Compiling include_juce_core.cpp
Compiling include_juce_data_structures.cpp
Compiling include_juce_dsp.cpp
Compiling include_juce_events.cpp
Compiling include_juce_graphics.cpp
Compiling include_juce_gui_basics.cpp
Compiling include_juce_gui_extra.cpp
Compiling include_juce_opengl.cpp
Linking Vial - App
../../../third_party/JUCE/modules/juce_core/text/juce_String.cpp: In Funktion »charToString«:
../../../third_party/JUCE/modules/juce_core/text/juce_CharPointer_UTF8.h:342:25: Warnung: Schreiben von 140625014776528 Byte in eine Region der Größe 1 [-Wstringop-overflow=]
  342 |                 *data++ = (CharType) (0x80 | (0x3f & (c >> (numExtraBytes * 6))));
      |                         ^
../../../third_party/JUCE/modules/juce_core/text/juce_CharPointer_UTF8.h:342:25: Warnung: Schreiben von 140625014708016 Byte in eine Region der Größe 1 [-Wstringop-overflow=]
make[1]: Verzeichnis ,,/usr/src/fremd/vital/standalone/builds/linux" wird verlassen
make -C plugin/builds/linux_vst VST CONFIG=Release AR=gcc-ar SIMDFLAGS="-msse2" GLFLAGS="" BUILD_DATE="2021 03 30 11 28"
make[1]: Verzeichnis ,,/usr/src/fremd/vital/plugin/builds/linux_vst" wird betreten
Compiling include_juce_audio_plugin_client_VST2.cpp
In Datei, eingebunden von ../../../third_party/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST2.cpp:26,
                 von ../../JuceLibraryCode/include_juce_audio_plugin_client_VST2.cpp:9:
../../../third_party/JUCE/modules/juce_audio_plugin_client/VST/juce_VST_Wrapper.cpp:87:10: schwerwiegender Fehler: pluginterfaces/vst2.x/aeffect.h: Datei oder Verzeichnis nicht gefunden
   87 | #include "pluginterfaces/vst2.x/aeffect.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Kompilierung beendet.
make[1]: *** [Makefile:201: build/intermediate/Release/include_juce_audio_plugin_client_VST2_dd551e08.o] Fehler 1
make[1]: Verzeichnis ,,/usr/src/fremd/vital/plugin/builds/linux_vst" wird verlassen
make: *** [Makefile:97: vst] Fehler 2

**Comment by artbody** [comment]
vitalium doesn*t compile

**Comment by falkTX** [comment]
Some files are from the VST2 SDK, which is not opensource and not even available anymore.

**Comment by mtytel** [comment]
Yeah you need the vst2 sdk to 'make all' but as falktTX said it's not publicly available.
Try:
make lv2
make vst3
make standalone

**Comment by artbody** [comment]
make lv2 compiles OK but

 make vst3
make -C plugin/builds/linux_vst VST3 CONFIG=Release AR=gcc-ar SIMDFLAGS="-msse2" GLFLAGS="" BUILD_DATE="2021 04 02 13 08"
make[1]: Verzeichnis „/usr/src/fremd/vital/plugin/builds/linux_vst“ wird betreten
Compiling include_juce_audio_plugin_client_VST3.cpp
In Datei, eingebunden von ../../../third_party/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp:26,
                 von ../../JuceLibraryCode/include_juce_audio_plugin_client_VST3.cpp:9:
../../../third_party/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3_Wrapper.cpp:32:24: Warnung: mehrere Token am Ende der Direktive #include
   32 |  #include <arpa/inet.h>^M
      |                        ^
In Datei, eingebunden von ../../../third_party/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp:26,
                 von ../../JuceLibraryCode/include_juce_audio_plugin_client_VST3.cpp:9:
../../../third_party/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3_Wrapper.cpp:33:7Warnung: mehrere Token am Ende der Direktive #endif [-Wendif-labels]
   33 | #endif^M
      |       ^
In Datei, eingebunden von ../../../third_party/JUCE/modules/juce_audio_plugin_client/juce_audio_plugin_client_VST3.cpp:26,
                 von ../../JuceLibraryCode/include_juce_audio_plugin_client_VST3.cpp:9:
../../../third_party/JUCE/modules/juce_audio_plugin_client/VST3/juce_VST3_Wrapper.cpp:69:11: schwerwiegender Fehler: pluginterfaces/vst2.x/vstfxstore.h: Datei oder Verzeichnis nicht gefunden
   69 |  #include "pluginterfaces/vst2.x/vstfxstore.h"
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Kompilierung beendet.
make[1]: *** [Makefile:206: build/intermediate/Release/include_juce_audio_plugin_client_VST3_dd633589.o] Fehler 1
make[1]: Verzeichnis „/usr/src/fremd/vital/plugin/builds/linux_vst“ wird verlassen
make: *** [Makefile:100: vst3] Fehler 2

and make standalone 
didn't

**Comment by artbody** [comment]
on gentoo linux -> ardour crashes 
means no interface of vial shows up
and then ardour it self is stopping to work
