### ISSUE TITLE
Permission to fork and use github actions to build binaries for StudioRack

### ISSUE THREAD

**Issue by kmturley** [mtytel/vital#26]
Thank-you for the great plugin work.

I would like to promote it by adding it to my site/app/command line tool:
https://studiorack.github.io/studiorack-site

This would involved forking your plugin and building binaries using GitHub actions. I have an example template here:
https://github.com/studiorack/studiorack-plugin-juce

Source code to the GitHub workflow which builds the JUCE plugin:
https://github.com/studiorack/studiorack-plugin-juce/blob/main/.github/workflows/release_projucer.yml

StudioRack is only for open-source plugins where there are direct links to binaries (no signups). However it looks like you prefer users to signup to download binaries? I don't want to circumvent your marketing activities.

Let me know your thoughts!
Kim

**Comment by Nan123721** [comment]
it's under GPL-3, you can do that as long as you provide the source for your version of the plugin.

**Comment by falkTX** [comment]
Except the use of trademarks. The README on this repo is clear on a few points.

**Comment by Nan123721** [comment]
Oh I see, never mind then.

**Comment by kmturley** [comment]
I find it odd that you can use the code for your own project, but not and credit the author!

Will fork and rebrand it in order to comply with the license. Thanks!

**Comment by mtytel** [comment]
To clarify a few things that came up in this:
 - When you fork you can't remove the copyright (e.g. from the top of the files) so my name remains there. The trademark restriction applies when you start distributing binaries.
 - If you use the code in a binary, that binary has to be licensed under the GPLv3.
