### ISSUE TITLE
Compiling fails with  fatal error: pluginterfaces/vst2.x/aeffect.h: No such file or directory

### ISSUE THREAD

**Issue by rajaneesh1973** [mtytel/vital#8]
I see only VST3 SDK...Can you please provide me pointer for VST2

**Comment by magnetophon** [comment]
The VST2 SDK can no longer be distributed.

This issue is a duplicate of https://github.com/mtytel/vital/issues/2

**Comment by tank-trax** [comment]
if you have the VST2_SDK just drop it in the same folder as VST3_SDK

**Comment by Be-ing** [comment]
I think we should replace the build system with a modern system (CMake) that can handle various options without hacking the build system scripts.

**Comment by rajaneesh1973** [comment]
Thank.. After dropping VST2_SDK, it compiled correctly..

in Makefile it is mentioned as JUCE_TARGET_APP := vial in path standalone/builds/linux . Was it a typo?

I changed it to vital. It compiled..But while running it gives an error

ERROR: Unable to load Firebase app options ([google-services-desktop.json, google-services.json] are missing or malformed)
ERROR: Failed to load default options when attempting to populate missing fields
ERROR: App ID and API key must be specified in App options.

**Comment by rajaneesh1973** [comment]
It worked well with -DNO_AUTH=1..Thanks...the issue is resolved.

**Comment by rajaneesh1973** [comment]
It worked well with -DNO_AUTH=1..Thanks...the issue is resolved.

**Comment by ricardoalcantara** [comment]
@rajaneesh1973 
How to add that -DNO_AUTH=1, I am having the same issue.

**Comment by tank-trax** [comment]
@ricardoalcantara check my branch for clues

**Comment by ricardoalcantara** [comment]
@tank-trax your branch worked for me, thanks
